// World currency dataset. `countries`/`regions` drive the searchable picker and
// the location-based default. `regions` are ISO-3166 alpha-2 codes; `decimals`
// overrides the default of 2 (Intl normally handles this, used for the fallback).
export type Currency = {
  code: string;
  symbol: string;
  label: string;
  countries: string[];
  regions: string[];
  decimals?: number;
};

// Ordered loosely by prevalence so the unsearched list leads with familiar codes.
export const CURRENCIES: Currency[] = [
  { code: "USD", symbol: "$", label: "US Dollar", countries: ["United States", "Ecuador", "El Salvador"], regions: ["US", "EC", "SV", "ZW", "TC", "VG"] },
  { code: "EUR", symbol: "€", label: "Euro", countries: ["Eurozone", "Germany", "France", "Italy", "Spain", "Netherlands", "Ireland", "Portugal", "Greece", "Austria", "Belgium", "Finland"], regions: ["DE", "FR", "IT", "ES", "NL", "IE", "PT", "GR", "AT", "BE", "FI", "LU", "SK", "SI", "EE", "LV", "LT", "CY", "MT", "HR"] },
  { code: "GBP", symbol: "£", label: "British Pound", countries: ["United Kingdom", "England", "Scotland", "Wales"], regions: ["GB"] },
  { code: "NGN", symbol: "₦", label: "Nigerian Naira", countries: ["Nigeria"], regions: ["NG"] },
  { code: "JPY", symbol: "¥", label: "Japanese Yen", countries: ["Japan"], regions: ["JP"], decimals: 0 },
  { code: "CNY", symbol: "¥", label: "Chinese Yuan", countries: ["China"], regions: ["CN"] },
  { code: "INR", symbol: "₹", label: "Indian Rupee", countries: ["India"], regions: ["IN"] },
  { code: "CAD", symbol: "$", label: "Canadian Dollar", countries: ["Canada"], regions: ["CA"] },
  { code: "AUD", symbol: "$", label: "Australian Dollar", countries: ["Australia"], regions: ["AU"] },
  { code: "CHF", symbol: "Fr", label: "Swiss Franc", countries: ["Switzerland", "Liechtenstein"], regions: ["CH", "LI"] },
  { code: "HKD", symbol: "$", label: "Hong Kong Dollar", countries: ["Hong Kong"], regions: ["HK"] },
  { code: "SGD", symbol: "$", label: "Singapore Dollar", countries: ["Singapore"], regions: ["SG"] },
  { code: "ZAR", symbol: "R", label: "South African Rand", countries: ["South Africa"], regions: ["ZA"] },
  { code: "BRL", symbol: "R$", label: "Brazilian Real", countries: ["Brazil"], regions: ["BR"] },
  { code: "MXN", symbol: "$", label: "Mexican Peso", countries: ["Mexico"], regions: ["MX"] },
  { code: "AED", symbol: "د.إ", label: "UAE Dirham", countries: ["United Arab Emirates", "Dubai"], regions: ["AE"] },
  { code: "SAR", symbol: "﷼", label: "Saudi Riyal", countries: ["Saudi Arabia"], regions: ["SA"] },
  { code: "KRW", symbol: "₩", label: "South Korean Won", countries: ["South Korea"], regions: ["KR"], decimals: 0 },
  { code: "RUB", symbol: "₽", label: "Russian Ruble", countries: ["Russia"], regions: ["RU"] },
  { code: "TRY", symbol: "₺", label: "Turkish Lira", countries: ["Turkey", "Türkiye"], regions: ["TR"] },
  { code: "SEK", symbol: "kr", label: "Swedish Krona", countries: ["Sweden"], regions: ["SE"] },
  { code: "NOK", symbol: "kr", label: "Norwegian Krone", countries: ["Norway"], regions: ["NO"] },
  { code: "DKK", symbol: "kr", label: "Danish Krone", countries: ["Denmark"], regions: ["DK"] },
  { code: "PLN", symbol: "zł", label: "Polish Zloty", countries: ["Poland"], regions: ["PL"] },
  { code: "IDR", symbol: "Rp", label: "Indonesian Rupiah", countries: ["Indonesia"], regions: ["ID"] },
  { code: "THB", symbol: "฿", label: "Thai Baht", countries: ["Thailand"], regions: ["TH"] },
  { code: "MYR", symbol: "RM", label: "Malaysian Ringgit", countries: ["Malaysia"], regions: ["MY"] },
  { code: "PHP", symbol: "₱", label: "Philippine Peso", countries: ["Philippines"], regions: ["PH"] },
  { code: "VND", symbol: "₫", label: "Vietnamese Dong", countries: ["Vietnam"], regions: ["VN"], decimals: 0 },
  { code: "PKR", symbol: "₨", label: "Pakistani Rupee", countries: ["Pakistan"], regions: ["PK"] },
  { code: "BDT", symbol: "৳", label: "Bangladeshi Taka", countries: ["Bangladesh"], regions: ["BD"] },
  { code: "EGP", symbol: "£", label: "Egyptian Pound", countries: ["Egypt"], regions: ["EG"] },
  { code: "KES", symbol: "KSh", label: "Kenyan Shilling", countries: ["Kenya"], regions: ["KE"] },
  { code: "GHS", symbol: "₵", label: "Ghanaian Cedi", countries: ["Ghana"], regions: ["GH"] },
  { code: "MAD", symbol: "د.م.", label: "Moroccan Dirham", countries: ["Morocco"], regions: ["MA"] },
  { code: "DZD", symbol: "د.ج", label: "Algerian Dinar", countries: ["Algeria"], regions: ["DZ"] },
  { code: "TND", symbol: "د.ت", label: "Tunisian Dinar", countries: ["Tunisia"], regions: ["TN"], decimals: 3 },
  { code: "UGX", symbol: "USh", label: "Ugandan Shilling", countries: ["Uganda"], regions: ["UG"], decimals: 0 },
  { code: "TZS", symbol: "TSh", label: "Tanzanian Shilling", countries: ["Tanzania"], regions: ["TZ"] },
  { code: "XOF", symbol: "CFA", label: "West African CFA Franc", countries: ["Senegal", "Ivory Coast", "Mali", "Benin", "Burkina Faso", "Togo", "Niger"], regions: ["SN", "CI", "ML", "BJ", "BF", "TG", "NE"], decimals: 0 },
  { code: "XAF", symbol: "FCFA", label: "Central African CFA Franc", countries: ["Cameroon", "Chad", "Gabon", "Congo", "Central African Republic"], regions: ["CM", "TD", "GA", "CG", "CF"], decimals: 0 },
  { code: "ILS", symbol: "₪", label: "Israeli New Shekel", countries: ["Israel"], regions: ["IL"] },
  { code: "QAR", symbol: "﷼", label: "Qatari Riyal", countries: ["Qatar"], regions: ["QA"] },
  { code: "KWD", symbol: "د.ك", label: "Kuwaiti Dinar", countries: ["Kuwait"], regions: ["KW"], decimals: 3 },
  { code: "BHD", symbol: ".د.ب", label: "Bahraini Dinar", countries: ["Bahrain"], regions: ["BH"], decimals: 3 },
  { code: "OMR", symbol: "﷼", label: "Omani Rial", countries: ["Oman"], regions: ["OM"], decimals: 3 },
  { code: "JOD", symbol: "د.ا", label: "Jordanian Dinar", countries: ["Jordan"], regions: ["JO"], decimals: 3 },
  { code: "LBP", symbol: "ل.ل", label: "Lebanese Pound", countries: ["Lebanon"], regions: ["LB"] },
  { code: "NZD", symbol: "$", label: "New Zealand Dollar", countries: ["New Zealand"], regions: ["NZ"] },
  { code: "CZK", symbol: "Kč", label: "Czech Koruna", countries: ["Czech Republic", "Czechia"], regions: ["CZ"] },
  { code: "HUF", symbol: "Ft", label: "Hungarian Forint", countries: ["Hungary"], regions: ["HU"] },
  { code: "RON", symbol: "lei", label: "Romanian Leu", countries: ["Romania"], regions: ["RO"] },
  { code: "BGN", symbol: "лв", label: "Bulgarian Lev", countries: ["Bulgaria"], regions: ["BG"] },
  { code: "UAH", symbol: "₴", label: "Ukrainian Hryvnia", countries: ["Ukraine"], regions: ["UA"] },
  { code: "CLP", symbol: "$", label: "Chilean Peso", countries: ["Chile"], regions: ["CL"], decimals: 0 },
  { code: "COP", symbol: "$", label: "Colombian Peso", countries: ["Colombia"], regions: ["CO"] },
  { code: "ARS", symbol: "$", label: "Argentine Peso", countries: ["Argentina"], regions: ["AR"] },
  { code: "PEN", symbol: "S/", label: "Peruvian Sol", countries: ["Peru"], regions: ["PE"] },
  { code: "UYU", symbol: "$U", label: "Uruguayan Peso", countries: ["Uruguay"], regions: ["UY"] },
  { code: "BOB", symbol: "Bs", label: "Bolivian Boliviano", countries: ["Bolivia"], regions: ["BO"] },
  { code: "DOP", symbol: "RD$", label: "Dominican Peso", countries: ["Dominican Republic"], regions: ["DO"] },
  { code: "GTQ", symbol: "Q", label: "Guatemalan Quetzal", countries: ["Guatemala"], regions: ["GT"] },
  { code: "CRC", symbol: "₡", label: "Costa Rican Colón", countries: ["Costa Rica"], regions: ["CR"] },
  { code: "TWD", symbol: "NT$", label: "New Taiwan Dollar", countries: ["Taiwan"], regions: ["TW"] },
  { code: "LKR", symbol: "Rs", label: "Sri Lankan Rupee", countries: ["Sri Lanka"], regions: ["LK"] },
  { code: "NPR", symbol: "₨", label: "Nepalese Rupee", countries: ["Nepal"], regions: ["NP"] },
  { code: "MMK", symbol: "K", label: "Myanmar Kyat", countries: ["Myanmar"], regions: ["MM"] },
  { code: "KHR", symbol: "៛", label: "Cambodian Riel", countries: ["Cambodia"], regions: ["KH"] },
  { code: "MOP", symbol: "MOP$", label: "Macanese Pataca", countries: ["Macau"], regions: ["MO"] },
  { code: "ISK", symbol: "kr", label: "Icelandic Króna", countries: ["Iceland"], regions: ["IS"], decimals: 0 },
  { code: "RSD", symbol: "дин", label: "Serbian Dinar", countries: ["Serbia"], regions: ["RS"] },
  { code: "ETB", symbol: "Br", label: "Ethiopian Birr", countries: ["Ethiopia"], regions: ["ET"] },
  { code: "ZMW", symbol: "ZK", label: "Zambian Kwacha", countries: ["Zambia"], regions: ["ZM"] },
  { code: "MUR", symbol: "₨", label: "Mauritian Rupee", countries: ["Mauritius"], regions: ["MU"] },
  { code: "BWP", symbol: "P", label: "Botswana Pula", countries: ["Botswana"], regions: ["BW"] },
  { code: "NAD", symbol: "$", label: "Namibian Dollar", countries: ["Namibia"], regions: ["NA"] },
  { code: "XCD", symbol: "$", label: "East Caribbean Dollar", countries: ["Antigua", "Grenada", "Saint Lucia"], regions: ["AG", "GD", "LC", "DM", "KN", "VC"] },
  { code: "JMD", symbol: "J$", label: "Jamaican Dollar", countries: ["Jamaica"], regions: ["JM"] },
  { code: "TTD", symbol: "TT$", label: "Trinidad & Tobago Dollar", countries: ["Trinidad and Tobago"], regions: ["TT"] },
  { code: "BHS", symbol: "$", label: "Bahamian Dollar", countries: ["Bahamas"], regions: ["BS"] },
  { code: "FJD", symbol: "$", label: "Fijian Dollar", countries: ["Fiji"], regions: ["FJ"] },
  { code: "PGK", symbol: "K", label: "Papua New Guinean Kina", countries: ["Papua New Guinea"], regions: ["PG"] },
  { code: "AZN", symbol: "₼", label: "Azerbaijani Manat", countries: ["Azerbaijan"], regions: ["AZ"] },
  { code: "GEL", symbol: "₾", label: "Georgian Lari", countries: ["Georgia"], regions: ["GE"] },
  { code: "AMD", symbol: "֏", label: "Armenian Dram", countries: ["Armenia"], regions: ["AM"] },
  { code: "KZT", symbol: "₸", label: "Kazakhstani Tenge", countries: ["Kazakhstan"], regions: ["KZ"] },
  { code: "UZS", symbol: "soʻm", label: "Uzbekistani Som", countries: ["Uzbekistan"], regions: ["UZ"] },
  { code: "BYN", symbol: "Br", label: "Belarusian Ruble", countries: ["Belarus"], regions: ["BY"] },
  { code: "IQD", symbol: "ع.د", label: "Iraqi Dinar", countries: ["Iraq"], regions: ["IQ"], decimals: 3 },
  { code: "IRR", symbol: "﷼", label: "Iranian Rial", countries: ["Iran"], regions: ["IR"] },
  { code: "AFN", symbol: "؋", label: "Afghan Afghani", countries: ["Afghanistan"], regions: ["AF"] },
  { code: "MNT", symbol: "₮", label: "Mongolian Tögrög", countries: ["Mongolia"], regions: ["MN"] },
  { code: "MZN", symbol: "MT", label: "Mozambican Metical", countries: ["Mozambique"], regions: ["MZ"] },
  { code: "AOA", symbol: "Kz", label: "Angolan Kwanza", countries: ["Angola"], regions: ["AO"] },
  { code: "CDF", symbol: "FC", label: "Congolese Franc", countries: ["DR Congo"], regions: ["CD"] },
  { code: "RWF", symbol: "FRw", label: "Rwandan Franc", countries: ["Rwanda"], regions: ["RW"], decimals: 0 },
  { code: "SDG", symbol: "ج.س.", label: "Sudanese Pound", countries: ["Sudan"], regions: ["SD"] },
  { code: "LYD", symbol: "ل.د", label: "Libyan Dinar", countries: ["Libya"], regions: ["LY"], decimals: 3 },
  { code: "SYP", symbol: "£", label: "Syrian Pound", countries: ["Syria"], regions: ["SY"] },
  { code: "YER", symbol: "﷼", label: "Yemeni Rial", countries: ["Yemen"], regions: ["YE"] },
  { code: "ALL", symbol: "L", label: "Albanian Lek", countries: ["Albania"], regions: ["AL"] },
  { code: "MKD", symbol: "ден", label: "Macedonian Denar", countries: ["North Macedonia"], regions: ["MK"] },
  { code: "BAM", symbol: "KM", label: "Bosnia-Herzegovina Mark", countries: ["Bosnia and Herzegovina"], regions: ["BA"] },
  { code: "MDL", symbol: "L", label: "Moldovan Leu", countries: ["Moldova"], regions: ["MD"] },
  { code: "PYG", symbol: "₲", label: "Paraguayan Guaraní", countries: ["Paraguay"], regions: ["PY"], decimals: 0 },
  { code: "HNL", symbol: "L", label: "Honduran Lempira", countries: ["Honduras"], regions: ["HN"] },
  { code: "NIO", symbol: "C$", label: "Nicaraguan Córdoba", countries: ["Nicaragua"], regions: ["NI"] },
  { code: "PAB", symbol: "B/.", label: "Panamanian Balboa", countries: ["Panama"], regions: ["PA"] },
  { code: "BND", symbol: "$", label: "Brunei Dollar", countries: ["Brunei"], regions: ["BN"] },
  { code: "LAK", symbol: "₭", label: "Lao Kip", countries: ["Laos"], regions: ["LA"] },
  { code: "MVR", symbol: ".ރ", label: "Maldivian Rufiyaa", countries: ["Maldives"], regions: ["MV"] },
  { code: "BTN", symbol: "Nu.", label: "Bhutanese Ngultrum", countries: ["Bhutan"], regions: ["BT"] },
];

export function currencyOf(code: string): Currency {
  return CURRENCIES.find((c) => c.code === code) ?? CURRENCIES[0];
}
